// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package pulser_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 5;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {
      logic [15:0] q;
    } switchval;
    struct packed {
      logic [15:0] q;
    } endval;
  } pulser_reg2hw_f1_cfg_reg_t;

  typedef struct packed {
    struct packed {
      logic [15:0] q;
    } switchval;
    struct packed {
      logic [15:0] q;
    } endval;
  } pulser_reg2hw_f2_cfg_reg_t;

  typedef struct packed {
    struct packed {
      logic [7:0]  q;
    } f1;
    struct packed {
      logic [7:0]  q;
    } f2;
    struct packed {
      logic [7:0]  q;
    } count_stop;
  } pulser_reg2hw_count_cfg_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } ready;
    struct packed {
      logic [2:0]  q;
    } state;
  } pulser_reg2hw_status_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } invert_out;
    struct packed {
      logic        q;
    } idle_out;
  } pulser_reg2hw_out_ctrl_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
      logic        de;
    } ready;
    struct packed {
      logic [2:0]  d;
      logic        de;
    } state;
  } pulser_hw2reg_status_reg_t;

  // Register -> HW type
  typedef struct packed {
    pulser_reg2hw_f1_cfg_reg_t f1_cfg; // [93:62]
    pulser_reg2hw_f2_cfg_reg_t f2_cfg; // [61:30]
    pulser_reg2hw_count_cfg_reg_t count_cfg; // [29:6]
    pulser_reg2hw_status_reg_t status; // [5:2]
    pulser_reg2hw_out_ctrl_reg_t out_ctrl; // [1:0]
  } pulser_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    pulser_hw2reg_status_reg_t status; // [5:0]
  } pulser_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] PULSER_F1_CFG_OFFSET = 5'h 0;
  parameter logic [BlockAw-1:0] PULSER_F2_CFG_OFFSET = 5'h 4;
  parameter logic [BlockAw-1:0] PULSER_COUNT_CFG_OFFSET = 5'h 8;
  parameter logic [BlockAw-1:0] PULSER_STATUS_OFFSET = 5'h c;
  parameter logic [BlockAw-1:0] PULSER_OUT_CTRL_OFFSET = 5'h 10;

  // Register index
  typedef enum int {
    PULSER_F1_CFG,
    PULSER_F2_CFG,
    PULSER_COUNT_CFG,
    PULSER_STATUS,
    PULSER_OUT_CTRL
  } pulser_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] PULSER_PERMIT [5] = '{
    4'b 1111, // index[0] PULSER_F1_CFG
    4'b 1111, // index[1] PULSER_F2_CFG
    4'b 0111, // index[2] PULSER_COUNT_CFG
    4'b 0001, // index[3] PULSER_STATUS
    4'b 0001  // index[4] PULSER_OUT_CTRL
  };

endpackage

