// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`

`include "prim_assert.sv"

module pulser_reg_top (
  input clk_i,
  input rst_ni,
  input  tlul_pkg::tl_h2d_t tl_i,
  output tlul_pkg::tl_d2h_t tl_o,
  // To HW
  output pulser_reg_pkg::pulser_reg2hw_t reg2hw, // Write
  input  pulser_reg_pkg::pulser_hw2reg_t hw2reg, // Read

  // Integrity check errors
  output logic intg_err_o
);

  import pulser_reg_pkg::* ;

  localparam int AW = 5;
  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [AW-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;
  logic reg_busy;

  tlul_pkg::tl_h2d_t tl_reg_h2d;
  tlul_pkg::tl_d2h_t tl_reg_d2h;


  // incoming payload check
  logic intg_err;
  tlul_cmd_intg_chk u_chk (
    .tl_i(tl_i),
    .err_o(intg_err)
  );

  // also check for spurious write enables
  logic reg_we_err;
  logic [4:0] reg_we_check;
  prim_reg_we_check #(
    .OneHotWidth(5)
  ) u_prim_reg_we_check (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .oh_i  (reg_we_check),
    .en_i  (reg_we && !addrmiss),
    .err_o (reg_we_err)
  );

  logic err_q;
  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
      err_q <= '0;
    end else if (intg_err || reg_we_err) begin
      err_q <= 1'b1;
    end
  end

  // integrity error output is permanent and should be used for alert generation
  // register errors are transactional
  assign intg_err_o = err_q | intg_err | reg_we_err;

  // outgoing integrity generation
  tlul_pkg::tl_d2h_t tl_o_pre;
  tlul_rsp_intg_gen #(
    .EnableRspIntgGen(1),
    .EnableDataIntgGen(1)
  ) u_rsp_intg_gen (
    .tl_i(tl_o_pre),
    .tl_o(tl_o)
  );

  assign tl_reg_h2d = tl_i;
  assign tl_o_pre   = tl_reg_d2h;

  tlul_adapter_reg #(
    .RegAw(AW),
    .RegDw(DW),
    .EnableDataIntgGen(0)
  ) u_reg_if (
    .clk_i  (clk_i),
    .rst_ni (rst_ni),

    .tl_i (tl_reg_h2d),
    .tl_o (tl_reg_d2h),

    .en_ifetch_i(prim_mubi_pkg::MuBi4False),
    .intg_error_o(),

    .we_o    (reg_we),
    .re_o    (reg_re),
    .addr_o  (reg_addr),
    .wdata_o (reg_wdata),
    .be_o    (reg_be),
    .busy_i  (reg_busy),
    .rdata_i (reg_rdata),
    .error_i (reg_error)
  );

  // cdc oversampling signals

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = addrmiss | wr_err | intg_err;

  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic f1_cfg_we;
  logic [15:0] f1_cfg_switch_qs;
  logic [15:0] f1_cfg_switch_wd;
  logic [15:0] f1_cfg_stop_qs;
  logic [15:0] f1_cfg_stop_wd;
  logic f2_cfg_we;
  logic [15:0] f2_cfg_switch_qs;
  logic [15:0] f2_cfg_switch_wd;
  logic [15:0] f2_cfg_stop_qs;
  logic [15:0] f2_cfg_stop_wd;
  logic count_cfg_we;
  logic [7:0] count_cfg_f1_qs;
  logic [7:0] count_cfg_f1_wd;
  logic [7:0] count_cfg_f2_qs;
  logic [7:0] count_cfg_f2_wd;
  logic [7:0] count_cfg_count_stop_qs;
  logic [7:0] count_cfg_count_stop_wd;
  logic status_ready_qs;
  logic [2:0] status_state_qs;
  logic out_ctrl_we;
  logic out_ctrl_invert_out_qs;
  logic out_ctrl_invert_out_wd;
  logic out_ctrl_idle_out_qs;
  logic out_ctrl_idle_out_wd;

  // Register instances
  // R[f1_cfg]: V(False)
  //   F[switch]: 15:0
  prim_subreg #(
    .DW      (16),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (16'h0),
    .Mubi    (1'b0)
  ) u_f1_cfg_switch (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (f1_cfg_we),
    .wd     (f1_cfg_switch_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.f1_cfg.switch.q),
    .ds     (),

    // to register interface (read)
    .qs     (f1_cfg_switch_qs)
  );

  //   F[stop]: 31:16
  prim_subreg #(
    .DW      (16),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (16'h0),
    .Mubi    (1'b0)
  ) u_f1_cfg_stop (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (f1_cfg_we),
    .wd     (f1_cfg_stop_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.f1_cfg.stop.q),
    .ds     (),

    // to register interface (read)
    .qs     (f1_cfg_stop_qs)
  );


  // R[f2_cfg]: V(False)
  //   F[switch]: 15:0
  prim_subreg #(
    .DW      (16),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (16'h0),
    .Mubi    (1'b0)
  ) u_f2_cfg_switch (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (f2_cfg_we),
    .wd     (f2_cfg_switch_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.f2_cfg.switch.q),
    .ds     (),

    // to register interface (read)
    .qs     (f2_cfg_switch_qs)
  );

  //   F[stop]: 31:16
  prim_subreg #(
    .DW      (16),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (16'h0),
    .Mubi    (1'b0)
  ) u_f2_cfg_stop (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (f2_cfg_we),
    .wd     (f2_cfg_stop_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.f2_cfg.stop.q),
    .ds     (),

    // to register interface (read)
    .qs     (f2_cfg_stop_qs)
  );


  // R[count_cfg]: V(False)
  //   F[f1]: 7:0
  prim_subreg #(
    .DW      (8),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (8'h0),
    .Mubi    (1'b0)
  ) u_count_cfg_f1 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (count_cfg_we),
    .wd     (count_cfg_f1_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.count_cfg.f1.q),
    .ds     (),

    // to register interface (read)
    .qs     (count_cfg_f1_qs)
  );

  //   F[f2]: 15:8
  prim_subreg #(
    .DW      (8),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (8'h0),
    .Mubi    (1'b0)
  ) u_count_cfg_f2 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (count_cfg_we),
    .wd     (count_cfg_f2_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.count_cfg.f2.q),
    .ds     (),

    // to register interface (read)
    .qs     (count_cfg_f2_qs)
  );

  //   F[count_stop]: 23:16
  prim_subreg #(
    .DW      (8),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (8'h0),
    .Mubi    (1'b0)
  ) u_count_cfg_count_stop (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (count_cfg_we),
    .wd     (count_cfg_count_stop_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.count_cfg.count_stop.q),
    .ds     (),

    // to register interface (read)
    .qs     (count_cfg_count_stop_qs)
  );


  // R[status]: V(False)
  //   F[ready]: 0:0
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRO),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_status_ready (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (1'b0),
    .wd     ('0),

    // from internal hardware
    .de     (hw2reg.status.ready.de),
    .d      (hw2reg.status.ready.d),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.status.ready.q),
    .ds     (),

    // to register interface (read)
    .qs     (status_ready_qs)
  );

  //   F[state]: 3:1
  prim_subreg #(
    .DW      (3),
    .SwAccess(prim_subreg_pkg::SwAccessRO),
    .RESVAL  (3'h0),
    .Mubi    (1'b0)
  ) u_status_state (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (1'b0),
    .wd     ('0),

    // from internal hardware
    .de     (hw2reg.status.state.de),
    .d      (hw2reg.status.state.d),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.status.state.q),
    .ds     (),

    // to register interface (read)
    .qs     (status_state_qs)
  );


  // R[out_ctrl]: V(False)
  //   F[invert_out]: 0:0
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_out_ctrl_invert_out (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (out_ctrl_we),
    .wd     (out_ctrl_invert_out_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.out_ctrl.invert_out.q),
    .ds     (),

    // to register interface (read)
    .qs     (out_ctrl_invert_out_qs)
  );

  //   F[idle_out]: 1:1
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_out_ctrl_idle_out (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (out_ctrl_we),
    .wd     (out_ctrl_idle_out_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.out_ctrl.idle_out.q),
    .ds     (),

    // to register interface (read)
    .qs     (out_ctrl_idle_out_qs)
  );



  logic [4:0] addr_hit;
  always_comb begin
    addr_hit[0] = (reg_addr == PULSER_F1_CFG_OFFSET);
    addr_hit[1] = (reg_addr == PULSER_F2_CFG_OFFSET);
    addr_hit[2] = (reg_addr == PULSER_COUNT_CFG_OFFSET);
    addr_hit[3] = (reg_addr == PULSER_STATUS_OFFSET);
    addr_hit[4] = (reg_addr == PULSER_OUT_CTRL_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[0] & (|(PULSER_PERMIT[0] & ~reg_be))) |
               (addr_hit[1] & (|(PULSER_PERMIT[1] & ~reg_be))) |
               (addr_hit[2] & (|(PULSER_PERMIT[2] & ~reg_be))) |
               (addr_hit[3] & (|(PULSER_PERMIT[3] & ~reg_be))) |
               (addr_hit[4] & (|(PULSER_PERMIT[4] & ~reg_be)))));
  end

  // Generate write-enables
  assign f1_cfg_we = addr_hit[0] & reg_we & !reg_error;

  assign f1_cfg_switch_wd = reg_wdata[15:0];

  assign f1_cfg_stop_wd = reg_wdata[31:16];
  assign f2_cfg_we = addr_hit[1] & reg_we & !reg_error;

  assign f2_cfg_switch_wd = reg_wdata[15:0];

  assign f2_cfg_stop_wd = reg_wdata[31:16];
  assign count_cfg_we = addr_hit[2] & reg_we & !reg_error;

  assign count_cfg_f1_wd = reg_wdata[7:0];

  assign count_cfg_f2_wd = reg_wdata[15:8];

  assign count_cfg_count_stop_wd = reg_wdata[23:16];
  assign out_ctrl_we = addr_hit[4] & reg_we & !reg_error;

  assign out_ctrl_invert_out_wd = reg_wdata[0];

  assign out_ctrl_idle_out_wd = reg_wdata[1];

  // Assign write-enables to checker logic vector.
  always_comb begin
    reg_we_check[0] = f1_cfg_we;
    reg_we_check[1] = f2_cfg_we;
    reg_we_check[2] = count_cfg_we;
    reg_we_check[3] = 1'b0;
    reg_we_check[4] = out_ctrl_we;
  end

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[15:0] = f1_cfg_switch_qs;
        reg_rdata_next[31:16] = f1_cfg_stop_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[15:0] = f2_cfg_switch_qs;
        reg_rdata_next[31:16] = f2_cfg_stop_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[7:0] = count_cfg_f1_qs;
        reg_rdata_next[15:8] = count_cfg_f2_qs;
        reg_rdata_next[23:16] = count_cfg_count_stop_qs;
      end

      addr_hit[3]: begin
        reg_rdata_next[0] = status_ready_qs;
        reg_rdata_next[3:1] = status_state_qs;
      end

      addr_hit[4]: begin
        reg_rdata_next[0] = out_ctrl_invert_out_qs;
        reg_rdata_next[1] = out_ctrl_idle_out_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // shadow busy
  logic shadow_busy;
  assign shadow_busy = 1'b0;

  // register busy
  assign reg_busy = shadow_busy;

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT_PULSE(wePulse, reg_we, clk_i, !rst_ni)
  `ASSERT_PULSE(rePulse, reg_re, clk_i, !rst_ni)

  `ASSERT(reAfterRv, $rose(reg_re || reg_we) |=> tl_o_pre.d_valid, clk_i, !rst_ni)

  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit), clk_i, !rst_ni)

  // this is formulated as an assumption such that the FPV testbenches do disprove this
  // property by mistake
  //`ASSUME(reqParity, tl_reg_h2d.a_valid |-> tl_reg_h2d.a_user.chk_en == tlul_pkg::CheckDis)

endmodule
