// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package pulser_reg_pkg;

  // Param list
  parameter int NumPulsers = 4;

  // Address widths within the block
  parameter int BlockAw = 6;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {
      logic [15:0] q;
    } switchval;
    struct packed {
      logic [15:0] q;
    } endval;
  } pulser_reg2hw_cfg_f1_mreg_t;

  typedef struct packed {
    struct packed {
      logic [15:0] q;
    } switchval;
    struct packed {
      logic [15:0] q;
    } endval;
  } pulser_reg2hw_cfg_f2_mreg_t;

  typedef struct packed {
    struct packed {
      logic [7:0]  q;
    } f1;
    struct packed {
      logic [7:0]  q;
    } f2;
    struct packed {
      logic [7:0]  q;
    } count_stop;
  } pulser_reg2hw_cfg_cnt_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } invert_out;
    struct packed {
      logic        q;
    } idle_out;
  } pulser_reg2hw_ctrl_out_mreg_t;

  typedef struct packed {
    struct packed {
      logic        q;
      logic        qe;
    } start;
    struct packed {
      logic        q;
      logic        qe;
    } stop;
  } pulser_reg2hw_ctrl_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
      logic        de;
    } ready;
    struct packed {
      logic [2:0]  d;
      logic        de;
    } state;
  } pulser_hw2reg_status_reg_t;

  // Register -> HW type
  typedef struct packed {
    pulser_reg2hw_cfg_f1_mreg_t [3:0] cfg_f1; // [291:164]
    pulser_reg2hw_cfg_f2_mreg_t [3:0] cfg_f2; // [163:36]
    pulser_reg2hw_cfg_cnt_reg_t cfg_cnt; // [35:12]
    pulser_reg2hw_ctrl_out_mreg_t [3:0] ctrl_out; // [11:4]
    pulser_reg2hw_ctrl_reg_t ctrl; // [3:0]
  } pulser_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    pulser_hw2reg_status_reg_t status; // [5:0]
  } pulser_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] PULSER_CFG_F1_0_OFFSET = 6'h 0;
  parameter logic [BlockAw-1:0] PULSER_CFG_F1_1_OFFSET = 6'h 4;
  parameter logic [BlockAw-1:0] PULSER_CFG_F1_2_OFFSET = 6'h 8;
  parameter logic [BlockAw-1:0] PULSER_CFG_F1_3_OFFSET = 6'h c;
  parameter logic [BlockAw-1:0] PULSER_CFG_F2_0_OFFSET = 6'h 10;
  parameter logic [BlockAw-1:0] PULSER_CFG_F2_1_OFFSET = 6'h 14;
  parameter logic [BlockAw-1:0] PULSER_CFG_F2_2_OFFSET = 6'h 18;
  parameter logic [BlockAw-1:0] PULSER_CFG_F2_3_OFFSET = 6'h 1c;
  parameter logic [BlockAw-1:0] PULSER_CFG_CNT_OFFSET = 6'h 20;
  parameter logic [BlockAw-1:0] PULSER_STATUS_OFFSET = 6'h 24;
  parameter logic [BlockAw-1:0] PULSER_CTRL_OUT_0_OFFSET = 6'h 28;
  parameter logic [BlockAw-1:0] PULSER_CTRL_OUT_1_OFFSET = 6'h 2c;
  parameter logic [BlockAw-1:0] PULSER_CTRL_OUT_2_OFFSET = 6'h 30;
  parameter logic [BlockAw-1:0] PULSER_CTRL_OUT_3_OFFSET = 6'h 34;
  parameter logic [BlockAw-1:0] PULSER_CTRL_OFFSET = 6'h 38;

  // Reset values for hwext registers and their fields
  parameter logic [1:0] PULSER_CTRL_RESVAL = 2'h 0;

  // Register index
  typedef enum int {
    PULSER_CFG_F1_0,
    PULSER_CFG_F1_1,
    PULSER_CFG_F1_2,
    PULSER_CFG_F1_3,
    PULSER_CFG_F2_0,
    PULSER_CFG_F2_1,
    PULSER_CFG_F2_2,
    PULSER_CFG_F2_3,
    PULSER_CFG_CNT,
    PULSER_STATUS,
    PULSER_CTRL_OUT_0,
    PULSER_CTRL_OUT_1,
    PULSER_CTRL_OUT_2,
    PULSER_CTRL_OUT_3,
    PULSER_CTRL
  } pulser_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] PULSER_PERMIT [15] = '{
    4'b 1111, // index[ 0] PULSER_CFG_F1_0
    4'b 1111, // index[ 1] PULSER_CFG_F1_1
    4'b 1111, // index[ 2] PULSER_CFG_F1_2
    4'b 1111, // index[ 3] PULSER_CFG_F1_3
    4'b 1111, // index[ 4] PULSER_CFG_F2_0
    4'b 1111, // index[ 5] PULSER_CFG_F2_1
    4'b 1111, // index[ 6] PULSER_CFG_F2_2
    4'b 1111, // index[ 7] PULSER_CFG_F2_3
    4'b 0111, // index[ 8] PULSER_CFG_CNT
    4'b 0001, // index[ 9] PULSER_STATUS
    4'b 0001, // index[10] PULSER_CTRL_OUT_0
    4'b 0001, // index[11] PULSER_CTRL_OUT_1
    4'b 0001, // index[12] PULSER_CTRL_OUT_2
    4'b 0001, // index[13] PULSER_CTRL_OUT_3
    4'b 0001  // index[14] PULSER_CTRL
  };

endpackage

