// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "common_cells/assertions.svh"

module pulser_reg_top #(
  parameter type reg_req_t = logic,
  parameter type reg_rsp_t = logic,
  parameter int AW = 7
) (
  input logic clk_i,
  input logic rst_ni,
  input  reg_req_t reg_req_i,
  output reg_rsp_t reg_rsp_o,
  // To HW
  output pulser_reg_pkg::pulser_reg2hw_t reg2hw, // Write
  input  pulser_reg_pkg::pulser_hw2reg_t hw2reg, // Read


  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);

  import pulser_reg_pkg::* ;

  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [AW-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  // Below register interface can be changed
  reg_req_t  reg_intf_req;
  reg_rsp_t  reg_intf_rsp;


  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;


  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr;
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic [15:0] cfg_f1_end_0_endval_0_qs;
  logic [15:0] cfg_f1_end_0_endval_0_wd;
  logic cfg_f1_end_0_endval_0_we;
  logic [15:0] cfg_f1_end_0_endval_1_qs;
  logic [15:0] cfg_f1_end_0_endval_1_wd;
  logic cfg_f1_end_0_endval_1_we;
  logic [15:0] cfg_f1_end_1_endval_2_qs;
  logic [15:0] cfg_f1_end_1_endval_2_wd;
  logic cfg_f1_end_1_endval_2_we;
  logic [15:0] cfg_f1_end_1_endval_3_qs;
  logic [15:0] cfg_f1_end_1_endval_3_wd;
  logic cfg_f1_end_1_endval_3_we;
  logic [15:0] cfg_f1_switch_0_switchval_0_qs;
  logic [15:0] cfg_f1_switch_0_switchval_0_wd;
  logic cfg_f1_switch_0_switchval_0_we;
  logic [15:0] cfg_f1_switch_0_switchval_1_qs;
  logic [15:0] cfg_f1_switch_0_switchval_1_wd;
  logic cfg_f1_switch_0_switchval_1_we;
  logic [15:0] cfg_f1_switch_1_switchval_2_qs;
  logic [15:0] cfg_f1_switch_1_switchval_2_wd;
  logic cfg_f1_switch_1_switchval_2_we;
  logic [15:0] cfg_f1_switch_1_switchval_3_qs;
  logic [15:0] cfg_f1_switch_1_switchval_3_wd;
  logic cfg_f1_switch_1_switchval_3_we;
  logic [15:0] cfg_f2_end_0_endval_0_qs;
  logic [15:0] cfg_f2_end_0_endval_0_wd;
  logic cfg_f2_end_0_endval_0_we;
  logic [15:0] cfg_f2_end_0_endval_1_qs;
  logic [15:0] cfg_f2_end_0_endval_1_wd;
  logic cfg_f2_end_0_endval_1_we;
  logic [15:0] cfg_f2_end_1_endval_2_qs;
  logic [15:0] cfg_f2_end_1_endval_2_wd;
  logic cfg_f2_end_1_endval_2_we;
  logic [15:0] cfg_f2_end_1_endval_3_qs;
  logic [15:0] cfg_f2_end_1_endval_3_wd;
  logic cfg_f2_end_1_endval_3_we;
  logic [15:0] cfg_f2_switch_0_switchval_0_qs;
  logic [15:0] cfg_f2_switch_0_switchval_0_wd;
  logic cfg_f2_switch_0_switchval_0_we;
  logic [15:0] cfg_f2_switch_0_switchval_1_qs;
  logic [15:0] cfg_f2_switch_0_switchval_1_wd;
  logic cfg_f2_switch_0_switchval_1_we;
  logic [15:0] cfg_f2_switch_1_switchval_2_qs;
  logic [15:0] cfg_f2_switch_1_switchval_2_wd;
  logic cfg_f2_switch_1_switchval_2_we;
  logic [15:0] cfg_f2_switch_1_switchval_3_qs;
  logic [15:0] cfg_f2_switch_1_switchval_3_wd;
  logic cfg_f2_switch_1_switchval_3_we;
  logic [7:0] cfg_cnt_f1_f1_0_qs;
  logic [7:0] cfg_cnt_f1_f1_0_wd;
  logic cfg_cnt_f1_f1_0_we;
  logic [7:0] cfg_cnt_f1_f1_1_qs;
  logic [7:0] cfg_cnt_f1_f1_1_wd;
  logic cfg_cnt_f1_f1_1_we;
  logic [7:0] cfg_cnt_f1_f1_2_qs;
  logic [7:0] cfg_cnt_f1_f1_2_wd;
  logic cfg_cnt_f1_f1_2_we;
  logic [7:0] cfg_cnt_f1_f1_3_qs;
  logic [7:0] cfg_cnt_f1_f1_3_wd;
  logic cfg_cnt_f1_f1_3_we;
  logic [7:0] cfg_cnt_f2_f2_0_qs;
  logic [7:0] cfg_cnt_f2_f2_0_wd;
  logic cfg_cnt_f2_f2_0_we;
  logic [7:0] cfg_cnt_f2_f2_1_qs;
  logic [7:0] cfg_cnt_f2_f2_1_wd;
  logic cfg_cnt_f2_f2_1_we;
  logic [7:0] cfg_cnt_f2_f2_2_qs;
  logic [7:0] cfg_cnt_f2_f2_2_wd;
  logic cfg_cnt_f2_f2_2_we;
  logic [7:0] cfg_cnt_f2_f2_3_qs;
  logic [7:0] cfg_cnt_f2_f2_3_wd;
  logic cfg_cnt_f2_f2_3_we;
  logic [7:0] cfg_cnt_stop_count_stop_0_qs;
  logic [7:0] cfg_cnt_stop_count_stop_0_wd;
  logic cfg_cnt_stop_count_stop_0_we;
  logic [7:0] cfg_cnt_stop_count_stop_1_qs;
  logic [7:0] cfg_cnt_stop_count_stop_1_wd;
  logic cfg_cnt_stop_count_stop_1_we;
  logic [7:0] cfg_cnt_stop_count_stop_2_qs;
  logic [7:0] cfg_cnt_stop_count_stop_2_wd;
  logic cfg_cnt_stop_count_stop_2_we;
  logic [7:0] cfg_cnt_stop_count_stop_3_qs;
  logic [7:0] cfg_cnt_stop_count_stop_3_wd;
  logic cfg_cnt_stop_count_stop_3_we;
  logic ready_ready_0_qs;
  logic ready_ready_1_qs;
  logic ready_ready_2_qs;
  logic ready_ready_3_qs;
  logic [2:0] state_state_0_qs;
  logic [2:0] state_state_1_qs;
  logic [2:0] state_state_2_qs;
  logic [2:0] state_state_3_qs;
  logic ctrl_inv_out_invert_out_0_qs;
  logic ctrl_inv_out_invert_out_0_wd;
  logic ctrl_inv_out_invert_out_0_we;
  logic ctrl_inv_out_invert_out_1_qs;
  logic ctrl_inv_out_invert_out_1_wd;
  logic ctrl_inv_out_invert_out_1_we;
  logic ctrl_inv_out_invert_out_2_qs;
  logic ctrl_inv_out_invert_out_2_wd;
  logic ctrl_inv_out_invert_out_2_we;
  logic ctrl_inv_out_invert_out_3_qs;
  logic ctrl_inv_out_invert_out_3_wd;
  logic ctrl_inv_out_invert_out_3_we;
  logic ctrl_idle_out_idle_out_0_qs;
  logic ctrl_idle_out_idle_out_0_wd;
  logic ctrl_idle_out_idle_out_0_we;
  logic ctrl_idle_out_idle_out_1_qs;
  logic ctrl_idle_out_idle_out_1_wd;
  logic ctrl_idle_out_idle_out_1_we;
  logic ctrl_idle_out_idle_out_2_qs;
  logic ctrl_idle_out_idle_out_2_wd;
  logic ctrl_idle_out_idle_out_2_we;
  logic ctrl_idle_out_idle_out_3_qs;
  logic ctrl_idle_out_idle_out_3_wd;
  logic ctrl_idle_out_idle_out_3_we;
  logic ctrl_start_start_0_wd;
  logic ctrl_start_start_0_we;
  logic ctrl_start_start_1_wd;
  logic ctrl_start_start_1_we;
  logic ctrl_start_start_2_wd;
  logic ctrl_start_start_2_we;
  logic ctrl_start_start_3_wd;
  logic ctrl_start_start_3_we;
  logic ctrl_stop_stop_0_wd;
  logic ctrl_stop_stop_0_we;
  logic ctrl_stop_stop_1_wd;
  logic ctrl_stop_stop_1_we;
  logic ctrl_stop_stop_2_wd;
  logic ctrl_stop_stop_2_we;
  logic ctrl_stop_stop_3_wd;
  logic ctrl_stop_stop_3_we;

  // Register instances

  // Subregister 0 of Multireg cfg_f1_end
  // R[cfg_f1_end_0]: V(False)

  // F[endval_0]: 15:0
  prim_subreg #(
    .DW      (16),
    .SWACCESS("RW"),
    .RESVAL  (16'h0)
  ) u_cfg_f1_end_0_endval_0 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cfg_f1_end_0_endval_0_we),
    .wd     (cfg_f1_end_0_endval_0_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cfg_f1_end[0].q ),

    // to register interface (read)
    .qs     (cfg_f1_end_0_endval_0_qs)
  );


  // F[endval_1]: 31:16
  prim_subreg #(
    .DW      (16),
    .SWACCESS("RW"),
    .RESVAL  (16'h0)
  ) u_cfg_f1_end_0_endval_1 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cfg_f1_end_0_endval_1_we),
    .wd     (cfg_f1_end_0_endval_1_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cfg_f1_end[1].q ),

    // to register interface (read)
    .qs     (cfg_f1_end_0_endval_1_qs)
  );


  // Subregister 2 of Multireg cfg_f1_end
  // R[cfg_f1_end_1]: V(False)

  // F[endval_2]: 15:0
  prim_subreg #(
    .DW      (16),
    .SWACCESS("RW"),
    .RESVAL  (16'h0)
  ) u_cfg_f1_end_1_endval_2 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cfg_f1_end_1_endval_2_we),
    .wd     (cfg_f1_end_1_endval_2_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cfg_f1_end[2].q ),

    // to register interface (read)
    .qs     (cfg_f1_end_1_endval_2_qs)
  );


  // F[endval_3]: 31:16
  prim_subreg #(
    .DW      (16),
    .SWACCESS("RW"),
    .RESVAL  (16'h0)
  ) u_cfg_f1_end_1_endval_3 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cfg_f1_end_1_endval_3_we),
    .wd     (cfg_f1_end_1_endval_3_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cfg_f1_end[3].q ),

    // to register interface (read)
    .qs     (cfg_f1_end_1_endval_3_qs)
  );




  // Subregister 0 of Multireg cfg_f1_switch
  // R[cfg_f1_switch_0]: V(False)

  // F[switchval_0]: 15:0
  prim_subreg #(
    .DW      (16),
    .SWACCESS("RW"),
    .RESVAL  (16'h0)
  ) u_cfg_f1_switch_0_switchval_0 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cfg_f1_switch_0_switchval_0_we),
    .wd     (cfg_f1_switch_0_switchval_0_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cfg_f1_switch[0].q ),

    // to register interface (read)
    .qs     (cfg_f1_switch_0_switchval_0_qs)
  );


  // F[switchval_1]: 31:16
  prim_subreg #(
    .DW      (16),
    .SWACCESS("RW"),
    .RESVAL  (16'h0)
  ) u_cfg_f1_switch_0_switchval_1 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cfg_f1_switch_0_switchval_1_we),
    .wd     (cfg_f1_switch_0_switchval_1_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cfg_f1_switch[1].q ),

    // to register interface (read)
    .qs     (cfg_f1_switch_0_switchval_1_qs)
  );


  // Subregister 2 of Multireg cfg_f1_switch
  // R[cfg_f1_switch_1]: V(False)

  // F[switchval_2]: 15:0
  prim_subreg #(
    .DW      (16),
    .SWACCESS("RW"),
    .RESVAL  (16'h0)
  ) u_cfg_f1_switch_1_switchval_2 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cfg_f1_switch_1_switchval_2_we),
    .wd     (cfg_f1_switch_1_switchval_2_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cfg_f1_switch[2].q ),

    // to register interface (read)
    .qs     (cfg_f1_switch_1_switchval_2_qs)
  );


  // F[switchval_3]: 31:16
  prim_subreg #(
    .DW      (16),
    .SWACCESS("RW"),
    .RESVAL  (16'h0)
  ) u_cfg_f1_switch_1_switchval_3 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cfg_f1_switch_1_switchval_3_we),
    .wd     (cfg_f1_switch_1_switchval_3_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cfg_f1_switch[3].q ),

    // to register interface (read)
    .qs     (cfg_f1_switch_1_switchval_3_qs)
  );




  // Subregister 0 of Multireg cfg_f2_end
  // R[cfg_f2_end_0]: V(False)

  // F[endval_0]: 15:0
  prim_subreg #(
    .DW      (16),
    .SWACCESS("RW"),
    .RESVAL  (16'h0)
  ) u_cfg_f2_end_0_endval_0 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cfg_f2_end_0_endval_0_we),
    .wd     (cfg_f2_end_0_endval_0_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cfg_f2_end[0].q ),

    // to register interface (read)
    .qs     (cfg_f2_end_0_endval_0_qs)
  );


  // F[endval_1]: 31:16
  prim_subreg #(
    .DW      (16),
    .SWACCESS("RW"),
    .RESVAL  (16'h0)
  ) u_cfg_f2_end_0_endval_1 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cfg_f2_end_0_endval_1_we),
    .wd     (cfg_f2_end_0_endval_1_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cfg_f2_end[1].q ),

    // to register interface (read)
    .qs     (cfg_f2_end_0_endval_1_qs)
  );


  // Subregister 2 of Multireg cfg_f2_end
  // R[cfg_f2_end_1]: V(False)

  // F[endval_2]: 15:0
  prim_subreg #(
    .DW      (16),
    .SWACCESS("RW"),
    .RESVAL  (16'h0)
  ) u_cfg_f2_end_1_endval_2 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cfg_f2_end_1_endval_2_we),
    .wd     (cfg_f2_end_1_endval_2_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cfg_f2_end[2].q ),

    // to register interface (read)
    .qs     (cfg_f2_end_1_endval_2_qs)
  );


  // F[endval_3]: 31:16
  prim_subreg #(
    .DW      (16),
    .SWACCESS("RW"),
    .RESVAL  (16'h0)
  ) u_cfg_f2_end_1_endval_3 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cfg_f2_end_1_endval_3_we),
    .wd     (cfg_f2_end_1_endval_3_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cfg_f2_end[3].q ),

    // to register interface (read)
    .qs     (cfg_f2_end_1_endval_3_qs)
  );




  // Subregister 0 of Multireg cfg_f2_switch
  // R[cfg_f2_switch_0]: V(False)

  // F[switchval_0]: 15:0
  prim_subreg #(
    .DW      (16),
    .SWACCESS("RW"),
    .RESVAL  (16'h0)
  ) u_cfg_f2_switch_0_switchval_0 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cfg_f2_switch_0_switchval_0_we),
    .wd     (cfg_f2_switch_0_switchval_0_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cfg_f2_switch[0].q ),

    // to register interface (read)
    .qs     (cfg_f2_switch_0_switchval_0_qs)
  );


  // F[switchval_1]: 31:16
  prim_subreg #(
    .DW      (16),
    .SWACCESS("RW"),
    .RESVAL  (16'h0)
  ) u_cfg_f2_switch_0_switchval_1 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cfg_f2_switch_0_switchval_1_we),
    .wd     (cfg_f2_switch_0_switchval_1_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cfg_f2_switch[1].q ),

    // to register interface (read)
    .qs     (cfg_f2_switch_0_switchval_1_qs)
  );


  // Subregister 2 of Multireg cfg_f2_switch
  // R[cfg_f2_switch_1]: V(False)

  // F[switchval_2]: 15:0
  prim_subreg #(
    .DW      (16),
    .SWACCESS("RW"),
    .RESVAL  (16'h0)
  ) u_cfg_f2_switch_1_switchval_2 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cfg_f2_switch_1_switchval_2_we),
    .wd     (cfg_f2_switch_1_switchval_2_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cfg_f2_switch[2].q ),

    // to register interface (read)
    .qs     (cfg_f2_switch_1_switchval_2_qs)
  );


  // F[switchval_3]: 31:16
  prim_subreg #(
    .DW      (16),
    .SWACCESS("RW"),
    .RESVAL  (16'h0)
  ) u_cfg_f2_switch_1_switchval_3 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cfg_f2_switch_1_switchval_3_we),
    .wd     (cfg_f2_switch_1_switchval_3_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cfg_f2_switch[3].q ),

    // to register interface (read)
    .qs     (cfg_f2_switch_1_switchval_3_qs)
  );




  // Subregister 0 of Multireg cfg_cnt_f1
  // R[cfg_cnt_f1]: V(False)

  // F[f1_0]: 7:0
  prim_subreg #(
    .DW      (8),
    .SWACCESS("RW"),
    .RESVAL  (8'h0)
  ) u_cfg_cnt_f1_f1_0 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cfg_cnt_f1_f1_0_we),
    .wd     (cfg_cnt_f1_f1_0_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cfg_cnt_f1[0].q ),

    // to register interface (read)
    .qs     (cfg_cnt_f1_f1_0_qs)
  );


  // F[f1_1]: 15:8
  prim_subreg #(
    .DW      (8),
    .SWACCESS("RW"),
    .RESVAL  (8'h0)
  ) u_cfg_cnt_f1_f1_1 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cfg_cnt_f1_f1_1_we),
    .wd     (cfg_cnt_f1_f1_1_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cfg_cnt_f1[1].q ),

    // to register interface (read)
    .qs     (cfg_cnt_f1_f1_1_qs)
  );


  // F[f1_2]: 23:16
  prim_subreg #(
    .DW      (8),
    .SWACCESS("RW"),
    .RESVAL  (8'h0)
  ) u_cfg_cnt_f1_f1_2 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cfg_cnt_f1_f1_2_we),
    .wd     (cfg_cnt_f1_f1_2_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cfg_cnt_f1[2].q ),

    // to register interface (read)
    .qs     (cfg_cnt_f1_f1_2_qs)
  );


  // F[f1_3]: 31:24
  prim_subreg #(
    .DW      (8),
    .SWACCESS("RW"),
    .RESVAL  (8'h0)
  ) u_cfg_cnt_f1_f1_3 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cfg_cnt_f1_f1_3_we),
    .wd     (cfg_cnt_f1_f1_3_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cfg_cnt_f1[3].q ),

    // to register interface (read)
    .qs     (cfg_cnt_f1_f1_3_qs)
  );




  // Subregister 0 of Multireg cfg_cnt_f2
  // R[cfg_cnt_f2]: V(False)

  // F[f2_0]: 7:0
  prim_subreg #(
    .DW      (8),
    .SWACCESS("RW"),
    .RESVAL  (8'h0)
  ) u_cfg_cnt_f2_f2_0 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cfg_cnt_f2_f2_0_we),
    .wd     (cfg_cnt_f2_f2_0_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cfg_cnt_f2[0].q ),

    // to register interface (read)
    .qs     (cfg_cnt_f2_f2_0_qs)
  );


  // F[f2_1]: 15:8
  prim_subreg #(
    .DW      (8),
    .SWACCESS("RW"),
    .RESVAL  (8'h0)
  ) u_cfg_cnt_f2_f2_1 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cfg_cnt_f2_f2_1_we),
    .wd     (cfg_cnt_f2_f2_1_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cfg_cnt_f2[1].q ),

    // to register interface (read)
    .qs     (cfg_cnt_f2_f2_1_qs)
  );


  // F[f2_2]: 23:16
  prim_subreg #(
    .DW      (8),
    .SWACCESS("RW"),
    .RESVAL  (8'h0)
  ) u_cfg_cnt_f2_f2_2 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cfg_cnt_f2_f2_2_we),
    .wd     (cfg_cnt_f2_f2_2_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cfg_cnt_f2[2].q ),

    // to register interface (read)
    .qs     (cfg_cnt_f2_f2_2_qs)
  );


  // F[f2_3]: 31:24
  prim_subreg #(
    .DW      (8),
    .SWACCESS("RW"),
    .RESVAL  (8'h0)
  ) u_cfg_cnt_f2_f2_3 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cfg_cnt_f2_f2_3_we),
    .wd     (cfg_cnt_f2_f2_3_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cfg_cnt_f2[3].q ),

    // to register interface (read)
    .qs     (cfg_cnt_f2_f2_3_qs)
  );




  // Subregister 0 of Multireg cfg_cnt_stop
  // R[cfg_cnt_stop]: V(False)

  // F[count_stop_0]: 7:0
  prim_subreg #(
    .DW      (8),
    .SWACCESS("RW"),
    .RESVAL  (8'h0)
  ) u_cfg_cnt_stop_count_stop_0 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cfg_cnt_stop_count_stop_0_we),
    .wd     (cfg_cnt_stop_count_stop_0_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cfg_cnt_stop[0].q ),

    // to register interface (read)
    .qs     (cfg_cnt_stop_count_stop_0_qs)
  );


  // F[count_stop_1]: 15:8
  prim_subreg #(
    .DW      (8),
    .SWACCESS("RW"),
    .RESVAL  (8'h0)
  ) u_cfg_cnt_stop_count_stop_1 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cfg_cnt_stop_count_stop_1_we),
    .wd     (cfg_cnt_stop_count_stop_1_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cfg_cnt_stop[1].q ),

    // to register interface (read)
    .qs     (cfg_cnt_stop_count_stop_1_qs)
  );


  // F[count_stop_2]: 23:16
  prim_subreg #(
    .DW      (8),
    .SWACCESS("RW"),
    .RESVAL  (8'h0)
  ) u_cfg_cnt_stop_count_stop_2 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cfg_cnt_stop_count_stop_2_we),
    .wd     (cfg_cnt_stop_count_stop_2_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cfg_cnt_stop[2].q ),

    // to register interface (read)
    .qs     (cfg_cnt_stop_count_stop_2_qs)
  );


  // F[count_stop_3]: 31:24
  prim_subreg #(
    .DW      (8),
    .SWACCESS("RW"),
    .RESVAL  (8'h0)
  ) u_cfg_cnt_stop_count_stop_3 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cfg_cnt_stop_count_stop_3_we),
    .wd     (cfg_cnt_stop_count_stop_3_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cfg_cnt_stop[3].q ),

    // to register interface (read)
    .qs     (cfg_cnt_stop_count_stop_3_qs)
  );




  // Subregister 0 of Multireg ready
  // R[ready]: V(False)

  // F[ready_0]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RO"),
    .RESVAL  (1'h0)
  ) u_ready_ready_0 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.ready[0].de),
    .d      (hw2reg.ready[0].d ),

    // to internal hardware
    .qe     (),
    .q      (),

    // to register interface (read)
    .qs     (ready_ready_0_qs)
  );


  // F[ready_1]: 1:1
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RO"),
    .RESVAL  (1'h0)
  ) u_ready_ready_1 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.ready[1].de),
    .d      (hw2reg.ready[1].d ),

    // to internal hardware
    .qe     (),
    .q      (),

    // to register interface (read)
    .qs     (ready_ready_1_qs)
  );


  // F[ready_2]: 2:2
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RO"),
    .RESVAL  (1'h0)
  ) u_ready_ready_2 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.ready[2].de),
    .d      (hw2reg.ready[2].d ),

    // to internal hardware
    .qe     (),
    .q      (),

    // to register interface (read)
    .qs     (ready_ready_2_qs)
  );


  // F[ready_3]: 3:3
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RO"),
    .RESVAL  (1'h0)
  ) u_ready_ready_3 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.ready[3].de),
    .d      (hw2reg.ready[3].d ),

    // to internal hardware
    .qe     (),
    .q      (),

    // to register interface (read)
    .qs     (ready_ready_3_qs)
  );




  // Subregister 0 of Multireg state
  // R[state]: V(False)

  // F[state_0]: 2:0
  prim_subreg #(
    .DW      (3),
    .SWACCESS("RO"),
    .RESVAL  (3'h0)
  ) u_state_state_0 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.state[0].de),
    .d      (hw2reg.state[0].d ),

    // to internal hardware
    .qe     (),
    .q      (),

    // to register interface (read)
    .qs     (state_state_0_qs)
  );


  // F[state_1]: 5:3
  prim_subreg #(
    .DW      (3),
    .SWACCESS("RO"),
    .RESVAL  (3'h0)
  ) u_state_state_1 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.state[1].de),
    .d      (hw2reg.state[1].d ),

    // to internal hardware
    .qe     (),
    .q      (),

    // to register interface (read)
    .qs     (state_state_1_qs)
  );


  // F[state_2]: 8:6
  prim_subreg #(
    .DW      (3),
    .SWACCESS("RO"),
    .RESVAL  (3'h0)
  ) u_state_state_2 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.state[2].de),
    .d      (hw2reg.state[2].d ),

    // to internal hardware
    .qe     (),
    .q      (),

    // to register interface (read)
    .qs     (state_state_2_qs)
  );


  // F[state_3]: 11:9
  prim_subreg #(
    .DW      (3),
    .SWACCESS("RO"),
    .RESVAL  (3'h0)
  ) u_state_state_3 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.state[3].de),
    .d      (hw2reg.state[3].d ),

    // to internal hardware
    .qe     (),
    .q      (),

    // to register interface (read)
    .qs     (state_state_3_qs)
  );




  // Subregister 0 of Multireg ctrl_inv_out
  // R[ctrl_inv_out]: V(False)

  // F[invert_out_0]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_ctrl_inv_out_invert_out_0 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (ctrl_inv_out_invert_out_0_we),
    .wd     (ctrl_inv_out_invert_out_0_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl_inv_out[0].q ),

    // to register interface (read)
    .qs     (ctrl_inv_out_invert_out_0_qs)
  );


  // F[invert_out_1]: 1:1
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_ctrl_inv_out_invert_out_1 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (ctrl_inv_out_invert_out_1_we),
    .wd     (ctrl_inv_out_invert_out_1_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl_inv_out[1].q ),

    // to register interface (read)
    .qs     (ctrl_inv_out_invert_out_1_qs)
  );


  // F[invert_out_2]: 2:2
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_ctrl_inv_out_invert_out_2 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (ctrl_inv_out_invert_out_2_we),
    .wd     (ctrl_inv_out_invert_out_2_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl_inv_out[2].q ),

    // to register interface (read)
    .qs     (ctrl_inv_out_invert_out_2_qs)
  );


  // F[invert_out_3]: 3:3
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_ctrl_inv_out_invert_out_3 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (ctrl_inv_out_invert_out_3_we),
    .wd     (ctrl_inv_out_invert_out_3_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl_inv_out[3].q ),

    // to register interface (read)
    .qs     (ctrl_inv_out_invert_out_3_qs)
  );




  // Subregister 0 of Multireg ctrl_idle_out
  // R[ctrl_idle_out]: V(False)

  // F[idle_out_0]: 1:1
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_ctrl_idle_out_idle_out_0 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (ctrl_idle_out_idle_out_0_we),
    .wd     (ctrl_idle_out_idle_out_0_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl_idle_out[0].q ),

    // to register interface (read)
    .qs     (ctrl_idle_out_idle_out_0_qs)
  );


  // F[idle_out_1]: 3:3
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_ctrl_idle_out_idle_out_1 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (ctrl_idle_out_idle_out_1_we),
    .wd     (ctrl_idle_out_idle_out_1_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl_idle_out[1].q ),

    // to register interface (read)
    .qs     (ctrl_idle_out_idle_out_1_qs)
  );


  // F[idle_out_2]: 5:5
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_ctrl_idle_out_idle_out_2 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (ctrl_idle_out_idle_out_2_we),
    .wd     (ctrl_idle_out_idle_out_2_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl_idle_out[2].q ),

    // to register interface (read)
    .qs     (ctrl_idle_out_idle_out_2_qs)
  );


  // F[idle_out_3]: 7:7
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_ctrl_idle_out_idle_out_3 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (ctrl_idle_out_idle_out_3_we),
    .wd     (ctrl_idle_out_idle_out_3_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl_idle_out[3].q ),

    // to register interface (read)
    .qs     (ctrl_idle_out_idle_out_3_qs)
  );




  // Subregister 0 of Multireg ctrl_start
  // R[ctrl_start]: V(True)

  // F[start_0]: 0:0
  prim_subreg_ext #(
    .DW    (1)
  ) u_ctrl_start_start_0 (
    .re     (1'b0),
    .we     (ctrl_start_start_0_we),
    .wd     (ctrl_start_start_0_wd),
    .d      ('0),
    .qre    (),
    .qe     (reg2hw.ctrl_start[0].qe),
    .q      (reg2hw.ctrl_start[0].q ),
    .qs     ()
  );


  // F[start_1]: 1:1
  prim_subreg_ext #(
    .DW    (1)
  ) u_ctrl_start_start_1 (
    .re     (1'b0),
    .we     (ctrl_start_start_1_we),
    .wd     (ctrl_start_start_1_wd),
    .d      ('0),
    .qre    (),
    .qe     (reg2hw.ctrl_start[1].qe),
    .q      (reg2hw.ctrl_start[1].q ),
    .qs     ()
  );


  // F[start_2]: 2:2
  prim_subreg_ext #(
    .DW    (1)
  ) u_ctrl_start_start_2 (
    .re     (1'b0),
    .we     (ctrl_start_start_2_we),
    .wd     (ctrl_start_start_2_wd),
    .d      ('0),
    .qre    (),
    .qe     (reg2hw.ctrl_start[2].qe),
    .q      (reg2hw.ctrl_start[2].q ),
    .qs     ()
  );


  // F[start_3]: 3:3
  prim_subreg_ext #(
    .DW    (1)
  ) u_ctrl_start_start_3 (
    .re     (1'b0),
    .we     (ctrl_start_start_3_we),
    .wd     (ctrl_start_start_3_wd),
    .d      ('0),
    .qre    (),
    .qe     (reg2hw.ctrl_start[3].qe),
    .q      (reg2hw.ctrl_start[3].q ),
    .qs     ()
  );




  // Subregister 0 of Multireg ctrl_stop
  // R[ctrl_stop]: V(True)

  // F[stop_0]: 1:1
  prim_subreg_ext #(
    .DW    (1)
  ) u_ctrl_stop_stop_0 (
    .re     (1'b0),
    .we     (ctrl_stop_stop_0_we),
    .wd     (ctrl_stop_stop_0_wd),
    .d      ('0),
    .qre    (),
    .qe     (reg2hw.ctrl_stop[0].qe),
    .q      (reg2hw.ctrl_stop[0].q ),
    .qs     ()
  );


  // F[stop_1]: 3:3
  prim_subreg_ext #(
    .DW    (1)
  ) u_ctrl_stop_stop_1 (
    .re     (1'b0),
    .we     (ctrl_stop_stop_1_we),
    .wd     (ctrl_stop_stop_1_wd),
    .d      ('0),
    .qre    (),
    .qe     (reg2hw.ctrl_stop[1].qe),
    .q      (reg2hw.ctrl_stop[1].q ),
    .qs     ()
  );


  // F[stop_2]: 5:5
  prim_subreg_ext #(
    .DW    (1)
  ) u_ctrl_stop_stop_2 (
    .re     (1'b0),
    .we     (ctrl_stop_stop_2_we),
    .wd     (ctrl_stop_stop_2_wd),
    .d      ('0),
    .qre    (),
    .qe     (reg2hw.ctrl_stop[2].qe),
    .q      (reg2hw.ctrl_stop[2].q ),
    .qs     ()
  );


  // F[stop_3]: 7:7
  prim_subreg_ext #(
    .DW    (1)
  ) u_ctrl_stop_stop_3 (
    .re     (1'b0),
    .we     (ctrl_stop_stop_3_we),
    .wd     (ctrl_stop_stop_3_wd),
    .d      ('0),
    .qre    (),
    .qe     (reg2hw.ctrl_stop[3].qe),
    .q      (reg2hw.ctrl_stop[3].q ),
    .qs     ()
  );





  logic [16:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[ 0] = (reg_addr == PULSER_CFG_F1_END_0_OFFSET);
    addr_hit[ 1] = (reg_addr == PULSER_CFG_F1_END_1_OFFSET);
    addr_hit[ 2] = (reg_addr == PULSER_CFG_F1_SWITCH_0_OFFSET);
    addr_hit[ 3] = (reg_addr == PULSER_CFG_F1_SWITCH_1_OFFSET);
    addr_hit[ 4] = (reg_addr == PULSER_CFG_F2_END_0_OFFSET);
    addr_hit[ 5] = (reg_addr == PULSER_CFG_F2_END_1_OFFSET);
    addr_hit[ 6] = (reg_addr == PULSER_CFG_F2_SWITCH_0_OFFSET);
    addr_hit[ 7] = (reg_addr == PULSER_CFG_F2_SWITCH_1_OFFSET);
    addr_hit[ 8] = (reg_addr == PULSER_CFG_CNT_F1_OFFSET);
    addr_hit[ 9] = (reg_addr == PULSER_CFG_CNT_F2_OFFSET);
    addr_hit[10] = (reg_addr == PULSER_CFG_CNT_STOP_OFFSET);
    addr_hit[11] = (reg_addr == PULSER_READY_OFFSET);
    addr_hit[12] = (reg_addr == PULSER_STATE_OFFSET);
    addr_hit[13] = (reg_addr == PULSER_CTRL_INV_OUT_OFFSET);
    addr_hit[14] = (reg_addr == PULSER_CTRL_IDLE_OUT_OFFSET);
    addr_hit[15] = (reg_addr == PULSER_CTRL_START_OFFSET);
    addr_hit[16] = (reg_addr == PULSER_CTRL_STOP_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[ 0] & (|(PULSER_PERMIT[ 0] & ~reg_be))) |
               (addr_hit[ 1] & (|(PULSER_PERMIT[ 1] & ~reg_be))) |
               (addr_hit[ 2] & (|(PULSER_PERMIT[ 2] & ~reg_be))) |
               (addr_hit[ 3] & (|(PULSER_PERMIT[ 3] & ~reg_be))) |
               (addr_hit[ 4] & (|(PULSER_PERMIT[ 4] & ~reg_be))) |
               (addr_hit[ 5] & (|(PULSER_PERMIT[ 5] & ~reg_be))) |
               (addr_hit[ 6] & (|(PULSER_PERMIT[ 6] & ~reg_be))) |
               (addr_hit[ 7] & (|(PULSER_PERMIT[ 7] & ~reg_be))) |
               (addr_hit[ 8] & (|(PULSER_PERMIT[ 8] & ~reg_be))) |
               (addr_hit[ 9] & (|(PULSER_PERMIT[ 9] & ~reg_be))) |
               (addr_hit[10] & (|(PULSER_PERMIT[10] & ~reg_be))) |
               (addr_hit[11] & (|(PULSER_PERMIT[11] & ~reg_be))) |
               (addr_hit[12] & (|(PULSER_PERMIT[12] & ~reg_be))) |
               (addr_hit[13] & (|(PULSER_PERMIT[13] & ~reg_be))) |
               (addr_hit[14] & (|(PULSER_PERMIT[14] & ~reg_be))) |
               (addr_hit[15] & (|(PULSER_PERMIT[15] & ~reg_be))) |
               (addr_hit[16] & (|(PULSER_PERMIT[16] & ~reg_be)))));
  end

  assign cfg_f1_end_0_endval_0_we = addr_hit[0] & reg_we & !reg_error;
  assign cfg_f1_end_0_endval_0_wd = reg_wdata[15:0];

  assign cfg_f1_end_0_endval_1_we = addr_hit[0] & reg_we & !reg_error;
  assign cfg_f1_end_0_endval_1_wd = reg_wdata[31:16];

  assign cfg_f1_end_1_endval_2_we = addr_hit[1] & reg_we & !reg_error;
  assign cfg_f1_end_1_endval_2_wd = reg_wdata[15:0];

  assign cfg_f1_end_1_endval_3_we = addr_hit[1] & reg_we & !reg_error;
  assign cfg_f1_end_1_endval_3_wd = reg_wdata[31:16];

  assign cfg_f1_switch_0_switchval_0_we = addr_hit[2] & reg_we & !reg_error;
  assign cfg_f1_switch_0_switchval_0_wd = reg_wdata[15:0];

  assign cfg_f1_switch_0_switchval_1_we = addr_hit[2] & reg_we & !reg_error;
  assign cfg_f1_switch_0_switchval_1_wd = reg_wdata[31:16];

  assign cfg_f1_switch_1_switchval_2_we = addr_hit[3] & reg_we & !reg_error;
  assign cfg_f1_switch_1_switchval_2_wd = reg_wdata[15:0];

  assign cfg_f1_switch_1_switchval_3_we = addr_hit[3] & reg_we & !reg_error;
  assign cfg_f1_switch_1_switchval_3_wd = reg_wdata[31:16];

  assign cfg_f2_end_0_endval_0_we = addr_hit[4] & reg_we & !reg_error;
  assign cfg_f2_end_0_endval_0_wd = reg_wdata[15:0];

  assign cfg_f2_end_0_endval_1_we = addr_hit[4] & reg_we & !reg_error;
  assign cfg_f2_end_0_endval_1_wd = reg_wdata[31:16];

  assign cfg_f2_end_1_endval_2_we = addr_hit[5] & reg_we & !reg_error;
  assign cfg_f2_end_1_endval_2_wd = reg_wdata[15:0];

  assign cfg_f2_end_1_endval_3_we = addr_hit[5] & reg_we & !reg_error;
  assign cfg_f2_end_1_endval_3_wd = reg_wdata[31:16];

  assign cfg_f2_switch_0_switchval_0_we = addr_hit[6] & reg_we & !reg_error;
  assign cfg_f2_switch_0_switchval_0_wd = reg_wdata[15:0];

  assign cfg_f2_switch_0_switchval_1_we = addr_hit[6] & reg_we & !reg_error;
  assign cfg_f2_switch_0_switchval_1_wd = reg_wdata[31:16];

  assign cfg_f2_switch_1_switchval_2_we = addr_hit[7] & reg_we & !reg_error;
  assign cfg_f2_switch_1_switchval_2_wd = reg_wdata[15:0];

  assign cfg_f2_switch_1_switchval_3_we = addr_hit[7] & reg_we & !reg_error;
  assign cfg_f2_switch_1_switchval_3_wd = reg_wdata[31:16];

  assign cfg_cnt_f1_f1_0_we = addr_hit[8] & reg_we & !reg_error;
  assign cfg_cnt_f1_f1_0_wd = reg_wdata[7:0];

  assign cfg_cnt_f1_f1_1_we = addr_hit[8] & reg_we & !reg_error;
  assign cfg_cnt_f1_f1_1_wd = reg_wdata[15:8];

  assign cfg_cnt_f1_f1_2_we = addr_hit[8] & reg_we & !reg_error;
  assign cfg_cnt_f1_f1_2_wd = reg_wdata[23:16];

  assign cfg_cnt_f1_f1_3_we = addr_hit[8] & reg_we & !reg_error;
  assign cfg_cnt_f1_f1_3_wd = reg_wdata[31:24];

  assign cfg_cnt_f2_f2_0_we = addr_hit[9] & reg_we & !reg_error;
  assign cfg_cnt_f2_f2_0_wd = reg_wdata[7:0];

  assign cfg_cnt_f2_f2_1_we = addr_hit[9] & reg_we & !reg_error;
  assign cfg_cnt_f2_f2_1_wd = reg_wdata[15:8];

  assign cfg_cnt_f2_f2_2_we = addr_hit[9] & reg_we & !reg_error;
  assign cfg_cnt_f2_f2_2_wd = reg_wdata[23:16];

  assign cfg_cnt_f2_f2_3_we = addr_hit[9] & reg_we & !reg_error;
  assign cfg_cnt_f2_f2_3_wd = reg_wdata[31:24];

  assign cfg_cnt_stop_count_stop_0_we = addr_hit[10] & reg_we & !reg_error;
  assign cfg_cnt_stop_count_stop_0_wd = reg_wdata[7:0];

  assign cfg_cnt_stop_count_stop_1_we = addr_hit[10] & reg_we & !reg_error;
  assign cfg_cnt_stop_count_stop_1_wd = reg_wdata[15:8];

  assign cfg_cnt_stop_count_stop_2_we = addr_hit[10] & reg_we & !reg_error;
  assign cfg_cnt_stop_count_stop_2_wd = reg_wdata[23:16];

  assign cfg_cnt_stop_count_stop_3_we = addr_hit[10] & reg_we & !reg_error;
  assign cfg_cnt_stop_count_stop_3_wd = reg_wdata[31:24];

  assign ctrl_inv_out_invert_out_0_we = addr_hit[13] & reg_we & !reg_error;
  assign ctrl_inv_out_invert_out_0_wd = reg_wdata[0];

  assign ctrl_inv_out_invert_out_1_we = addr_hit[13] & reg_we & !reg_error;
  assign ctrl_inv_out_invert_out_1_wd = reg_wdata[1];

  assign ctrl_inv_out_invert_out_2_we = addr_hit[13] & reg_we & !reg_error;
  assign ctrl_inv_out_invert_out_2_wd = reg_wdata[2];

  assign ctrl_inv_out_invert_out_3_we = addr_hit[13] & reg_we & !reg_error;
  assign ctrl_inv_out_invert_out_3_wd = reg_wdata[3];

  assign ctrl_idle_out_idle_out_0_we = addr_hit[14] & reg_we & !reg_error;
  assign ctrl_idle_out_idle_out_0_wd = reg_wdata[1];

  assign ctrl_idle_out_idle_out_1_we = addr_hit[14] & reg_we & !reg_error;
  assign ctrl_idle_out_idle_out_1_wd = reg_wdata[3];

  assign ctrl_idle_out_idle_out_2_we = addr_hit[14] & reg_we & !reg_error;
  assign ctrl_idle_out_idle_out_2_wd = reg_wdata[5];

  assign ctrl_idle_out_idle_out_3_we = addr_hit[14] & reg_we & !reg_error;
  assign ctrl_idle_out_idle_out_3_wd = reg_wdata[7];

  assign ctrl_start_start_0_we = addr_hit[15] & reg_we & !reg_error;
  assign ctrl_start_start_0_wd = reg_wdata[0];

  assign ctrl_start_start_1_we = addr_hit[15] & reg_we & !reg_error;
  assign ctrl_start_start_1_wd = reg_wdata[1];

  assign ctrl_start_start_2_we = addr_hit[15] & reg_we & !reg_error;
  assign ctrl_start_start_2_wd = reg_wdata[2];

  assign ctrl_start_start_3_we = addr_hit[15] & reg_we & !reg_error;
  assign ctrl_start_start_3_wd = reg_wdata[3];

  assign ctrl_stop_stop_0_we = addr_hit[16] & reg_we & !reg_error;
  assign ctrl_stop_stop_0_wd = reg_wdata[1];

  assign ctrl_stop_stop_1_we = addr_hit[16] & reg_we & !reg_error;
  assign ctrl_stop_stop_1_wd = reg_wdata[3];

  assign ctrl_stop_stop_2_we = addr_hit[16] & reg_we & !reg_error;
  assign ctrl_stop_stop_2_wd = reg_wdata[5];

  assign ctrl_stop_stop_3_we = addr_hit[16] & reg_we & !reg_error;
  assign ctrl_stop_stop_3_wd = reg_wdata[7];

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[15:0] = cfg_f1_end_0_endval_0_qs;
        reg_rdata_next[31:16] = cfg_f1_end_0_endval_1_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[15:0] = cfg_f1_end_1_endval_2_qs;
        reg_rdata_next[31:16] = cfg_f1_end_1_endval_3_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[15:0] = cfg_f1_switch_0_switchval_0_qs;
        reg_rdata_next[31:16] = cfg_f1_switch_0_switchval_1_qs;
      end

      addr_hit[3]: begin
        reg_rdata_next[15:0] = cfg_f1_switch_1_switchval_2_qs;
        reg_rdata_next[31:16] = cfg_f1_switch_1_switchval_3_qs;
      end

      addr_hit[4]: begin
        reg_rdata_next[15:0] = cfg_f2_end_0_endval_0_qs;
        reg_rdata_next[31:16] = cfg_f2_end_0_endval_1_qs;
      end

      addr_hit[5]: begin
        reg_rdata_next[15:0] = cfg_f2_end_1_endval_2_qs;
        reg_rdata_next[31:16] = cfg_f2_end_1_endval_3_qs;
      end

      addr_hit[6]: begin
        reg_rdata_next[15:0] = cfg_f2_switch_0_switchval_0_qs;
        reg_rdata_next[31:16] = cfg_f2_switch_0_switchval_1_qs;
      end

      addr_hit[7]: begin
        reg_rdata_next[15:0] = cfg_f2_switch_1_switchval_2_qs;
        reg_rdata_next[31:16] = cfg_f2_switch_1_switchval_3_qs;
      end

      addr_hit[8]: begin
        reg_rdata_next[7:0] = cfg_cnt_f1_f1_0_qs;
        reg_rdata_next[15:8] = cfg_cnt_f1_f1_1_qs;
        reg_rdata_next[23:16] = cfg_cnt_f1_f1_2_qs;
        reg_rdata_next[31:24] = cfg_cnt_f1_f1_3_qs;
      end

      addr_hit[9]: begin
        reg_rdata_next[7:0] = cfg_cnt_f2_f2_0_qs;
        reg_rdata_next[15:8] = cfg_cnt_f2_f2_1_qs;
        reg_rdata_next[23:16] = cfg_cnt_f2_f2_2_qs;
        reg_rdata_next[31:24] = cfg_cnt_f2_f2_3_qs;
      end

      addr_hit[10]: begin
        reg_rdata_next[7:0] = cfg_cnt_stop_count_stop_0_qs;
        reg_rdata_next[15:8] = cfg_cnt_stop_count_stop_1_qs;
        reg_rdata_next[23:16] = cfg_cnt_stop_count_stop_2_qs;
        reg_rdata_next[31:24] = cfg_cnt_stop_count_stop_3_qs;
      end

      addr_hit[11]: begin
        reg_rdata_next[0] = ready_ready_0_qs;
        reg_rdata_next[1] = ready_ready_1_qs;
        reg_rdata_next[2] = ready_ready_2_qs;
        reg_rdata_next[3] = ready_ready_3_qs;
      end

      addr_hit[12]: begin
        reg_rdata_next[2:0] = state_state_0_qs;
        reg_rdata_next[5:3] = state_state_1_qs;
        reg_rdata_next[8:6] = state_state_2_qs;
        reg_rdata_next[11:9] = state_state_3_qs;
      end

      addr_hit[13]: begin
        reg_rdata_next[0] = ctrl_inv_out_invert_out_0_qs;
        reg_rdata_next[1] = ctrl_inv_out_invert_out_1_qs;
        reg_rdata_next[2] = ctrl_inv_out_invert_out_2_qs;
        reg_rdata_next[3] = ctrl_inv_out_invert_out_3_qs;
      end

      addr_hit[14]: begin
        reg_rdata_next[1] = ctrl_idle_out_idle_out_0_qs;
        reg_rdata_next[3] = ctrl_idle_out_idle_out_1_qs;
        reg_rdata_next[5] = ctrl_idle_out_idle_out_2_qs;
        reg_rdata_next[7] = ctrl_idle_out_idle_out_3_qs;
      end

      addr_hit[15]: begin
        reg_rdata_next[0] = '0;
        reg_rdata_next[1] = '0;
        reg_rdata_next[2] = '0;
        reg_rdata_next[3] = '0;
      end

      addr_hit[16]: begin
        reg_rdata_next[1] = '0;
        reg_rdata_next[3] = '0;
        reg_rdata_next[5] = '0;
        reg_rdata_next[7] = '0;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule

module pulser_reg_top_intf
#(
  parameter int AW = 7,
  localparam int DW = 32
) (
  input logic clk_i,
  input logic rst_ni,
  REG_BUS.in  regbus_slave,
  // To HW
  output pulser_reg_pkg::pulser_reg2hw_t reg2hw, // Write
  input  pulser_reg_pkg::pulser_hw2reg_t hw2reg, // Read
  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);
 localparam int unsigned STRB_WIDTH = DW/8;

`include "register_interface/typedef.svh"
`include "register_interface/assign.svh"

  // Define structs for reg_bus
  typedef logic [AW-1:0] addr_t;
  typedef logic [DW-1:0] data_t;
  typedef logic [STRB_WIDTH-1:0] strb_t;
  `REG_BUS_TYPEDEF_ALL(reg_bus, addr_t, data_t, strb_t)

  reg_bus_req_t s_reg_req;
  reg_bus_rsp_t s_reg_rsp;
  
  // Assign SV interface to structs
  `REG_BUS_ASSIGN_TO_REQ(s_reg_req, regbus_slave)
  `REG_BUS_ASSIGN_FROM_RSP(regbus_slave, s_reg_rsp)

  

  pulser_reg_top #(
    .reg_req_t(reg_bus_req_t),
    .reg_rsp_t(reg_bus_rsp_t),
    .AW(AW)
  ) i_regs (
    .clk_i,
    .rst_ni,
    .reg_req_i(s_reg_req),
    .reg_rsp_o(s_reg_rsp),
    .reg2hw, // Write
    .hw2reg, // Read
    .devmode_i
  );
  
endmodule


