// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "common_cells/assertions.svh"

module pulser_core_reg_top #(
  parameter type reg_req_t = logic,
  parameter type reg_rsp_t = logic,
  parameter int AW = 5
) (
  input logic clk_i,
  input logic rst_ni,
  input  reg_req_t reg_req_i,
  output reg_rsp_t reg_rsp_o,
  // To HW
  output pulser_core_reg_pkg::pulser_core_reg2hw_t reg2hw, // Write
  input  pulser_core_reg_pkg::pulser_core_hw2reg_t hw2reg, // Read


  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);

  import pulser_core_reg_pkg::* ;

  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [BlockAw-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  // Below register interface can be changed
  reg_req_t  reg_intf_req;
  reg_rsp_t  reg_intf_rsp;


  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;


  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr[BlockAw-1:0];
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic [15:0] cfg_f1_switchval_qs;
  logic [15:0] cfg_f1_switchval_wd;
  logic cfg_f1_switchval_we;
  logic [15:0] cfg_f1_endval_qs;
  logic [15:0] cfg_f1_endval_wd;
  logic cfg_f1_endval_we;
  logic [15:0] cfg_f2_switchval_qs;
  logic [15:0] cfg_f2_switchval_wd;
  logic cfg_f2_switchval_we;
  logic [15:0] cfg_f2_endval_qs;
  logic [15:0] cfg_f2_endval_wd;
  logic cfg_f2_endval_we;
  logic [7:0] cfg_cnt_f1_qs;
  logic [7:0] cfg_cnt_f1_wd;
  logic cfg_cnt_f1_we;
  logic [7:0] cfg_cnt_f2_qs;
  logic [7:0] cfg_cnt_f2_wd;
  logic cfg_cnt_f2_we;
  logic [7:0] cfg_cnt_cnt_stop_qs;
  logic [7:0] cfg_cnt_cnt_stop_wd;
  logic cfg_cnt_cnt_stop_we;
  logic status_ready_qs;
  logic [2:0] status_state_qs;
  logic ctrl_out_invert_out_qs;
  logic ctrl_out_invert_out_wd;
  logic ctrl_out_invert_out_we;
  logic ctrl_out_idle_out_qs;
  logic ctrl_out_idle_out_wd;
  logic ctrl_out_idle_out_we;

  // Register instances
  // R[cfg_f1]: V(False)

  //   F[switchval]: 15:0
  prim_subreg #(
    .DW      (16),
    .SWACCESS("RW"),
    .RESVAL  (16'h0)
  ) u_cfg_f1_switchval (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cfg_f1_switchval_we),
    .wd     (cfg_f1_switchval_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cfg_f1.switchval.q ),

    // to register interface (read)
    .qs     (cfg_f1_switchval_qs)
  );


  //   F[endval]: 31:16
  prim_subreg #(
    .DW      (16),
    .SWACCESS("RW"),
    .RESVAL  (16'h0)
  ) u_cfg_f1_endval (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cfg_f1_endval_we),
    .wd     (cfg_f1_endval_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cfg_f1.endval.q ),

    // to register interface (read)
    .qs     (cfg_f1_endval_qs)
  );


  // R[cfg_f2]: V(False)

  //   F[switchval]: 15:0
  prim_subreg #(
    .DW      (16),
    .SWACCESS("RW"),
    .RESVAL  (16'h0)
  ) u_cfg_f2_switchval (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cfg_f2_switchval_we),
    .wd     (cfg_f2_switchval_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cfg_f2.switchval.q ),

    // to register interface (read)
    .qs     (cfg_f2_switchval_qs)
  );


  //   F[endval]: 31:16
  prim_subreg #(
    .DW      (16),
    .SWACCESS("RW"),
    .RESVAL  (16'h0)
  ) u_cfg_f2_endval (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cfg_f2_endval_we),
    .wd     (cfg_f2_endval_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cfg_f2.endval.q ),

    // to register interface (read)
    .qs     (cfg_f2_endval_qs)
  );


  // R[cfg_cnt]: V(False)

  //   F[f1]: 7:0
  prim_subreg #(
    .DW      (8),
    .SWACCESS("RW"),
    .RESVAL  (8'h0)
  ) u_cfg_cnt_f1 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cfg_cnt_f1_we),
    .wd     (cfg_cnt_f1_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cfg_cnt.f1.q ),

    // to register interface (read)
    .qs     (cfg_cnt_f1_qs)
  );


  //   F[f2]: 15:8
  prim_subreg #(
    .DW      (8),
    .SWACCESS("RW"),
    .RESVAL  (8'h0)
  ) u_cfg_cnt_f2 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cfg_cnt_f2_we),
    .wd     (cfg_cnt_f2_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cfg_cnt.f2.q ),

    // to register interface (read)
    .qs     (cfg_cnt_f2_qs)
  );


  //   F[cnt_stop]: 23:16
  prim_subreg #(
    .DW      (8),
    .SWACCESS("RW"),
    .RESVAL  (8'h0)
  ) u_cfg_cnt_cnt_stop (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (cfg_cnt_cnt_stop_we),
    .wd     (cfg_cnt_cnt_stop_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.cfg_cnt.cnt_stop.q ),

    // to register interface (read)
    .qs     (cfg_cnt_cnt_stop_qs)
  );


  // R[status]: V(False)

  //   F[ready]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RO"),
    .RESVAL  (1'h0)
  ) u_status_ready (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.status.ready.de),
    .d      (hw2reg.status.ready.d ),

    // to internal hardware
    .qe     (),
    .q      (),

    // to register interface (read)
    .qs     (status_ready_qs)
  );


  //   F[state]: 3:1
  prim_subreg #(
    .DW      (3),
    .SWACCESS("RO"),
    .RESVAL  (3'h0)
  ) u_status_state (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.status.state.de),
    .d      (hw2reg.status.state.d ),

    // to internal hardware
    .qe     (),
    .q      (),

    // to register interface (read)
    .qs     (status_state_qs)
  );


  // R[ctrl_out]: V(False)

  //   F[invert_out]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_ctrl_out_invert_out (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (ctrl_out_invert_out_we),
    .wd     (ctrl_out_invert_out_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl_out.invert_out.q ),

    // to register interface (read)
    .qs     (ctrl_out_invert_out_qs)
  );


  //   F[idle_out]: 1:1
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_ctrl_out_idle_out (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (ctrl_out_idle_out_we),
    .wd     (ctrl_out_idle_out_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl_out.idle_out.q ),

    // to register interface (read)
    .qs     (ctrl_out_idle_out_qs)
  );




  logic [4:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[0] = (reg_addr == PULSER_CORE_CFG_F1_OFFSET);
    addr_hit[1] = (reg_addr == PULSER_CORE_CFG_F2_OFFSET);
    addr_hit[2] = (reg_addr == PULSER_CORE_CFG_CNT_OFFSET);
    addr_hit[3] = (reg_addr == PULSER_CORE_STATUS_OFFSET);
    addr_hit[4] = (reg_addr == PULSER_CORE_CTRL_OUT_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[0] & (|(PULSER_CORE_PERMIT[0] & ~reg_be))) |
               (addr_hit[1] & (|(PULSER_CORE_PERMIT[1] & ~reg_be))) |
               (addr_hit[2] & (|(PULSER_CORE_PERMIT[2] & ~reg_be))) |
               (addr_hit[3] & (|(PULSER_CORE_PERMIT[3] & ~reg_be))) |
               (addr_hit[4] & (|(PULSER_CORE_PERMIT[4] & ~reg_be)))));
  end

  assign cfg_f1_switchval_we = addr_hit[0] & reg_we & !reg_error;
  assign cfg_f1_switchval_wd = reg_wdata[15:0];

  assign cfg_f1_endval_we = addr_hit[0] & reg_we & !reg_error;
  assign cfg_f1_endval_wd = reg_wdata[31:16];

  assign cfg_f2_switchval_we = addr_hit[1] & reg_we & !reg_error;
  assign cfg_f2_switchval_wd = reg_wdata[15:0];

  assign cfg_f2_endval_we = addr_hit[1] & reg_we & !reg_error;
  assign cfg_f2_endval_wd = reg_wdata[31:16];

  assign cfg_cnt_f1_we = addr_hit[2] & reg_we & !reg_error;
  assign cfg_cnt_f1_wd = reg_wdata[7:0];

  assign cfg_cnt_f2_we = addr_hit[2] & reg_we & !reg_error;
  assign cfg_cnt_f2_wd = reg_wdata[15:8];

  assign cfg_cnt_cnt_stop_we = addr_hit[2] & reg_we & !reg_error;
  assign cfg_cnt_cnt_stop_wd = reg_wdata[23:16];

  assign ctrl_out_invert_out_we = addr_hit[4] & reg_we & !reg_error;
  assign ctrl_out_invert_out_wd = reg_wdata[0];

  assign ctrl_out_idle_out_we = addr_hit[4] & reg_we & !reg_error;
  assign ctrl_out_idle_out_wd = reg_wdata[1];

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[15:0] = cfg_f1_switchval_qs;
        reg_rdata_next[31:16] = cfg_f1_endval_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[15:0] = cfg_f2_switchval_qs;
        reg_rdata_next[31:16] = cfg_f2_endval_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[7:0] = cfg_cnt_f1_qs;
        reg_rdata_next[15:8] = cfg_cnt_f2_qs;
        reg_rdata_next[23:16] = cfg_cnt_cnt_stop_qs;
      end

      addr_hit[3]: begin
        reg_rdata_next[0] = status_ready_qs;
        reg_rdata_next[3:1] = status_state_qs;
      end

      addr_hit[4]: begin
        reg_rdata_next[0] = ctrl_out_invert_out_qs;
        reg_rdata_next[1] = ctrl_out_idle_out_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule

module pulser_core_reg_top_intf
#(
  parameter int AW = 5,
  localparam int DW = 32
) (
  input logic clk_i,
  input logic rst_ni,
  REG_BUS.in  regbus_slave,
  // To HW
  output pulser_core_reg_pkg::pulser_core_reg2hw_t reg2hw, // Write
  input  pulser_core_reg_pkg::pulser_core_hw2reg_t hw2reg, // Read
  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);
 localparam int unsigned STRB_WIDTH = DW/8;

`include "register_interface/typedef.svh"
`include "register_interface/assign.svh"

  // Define structs for reg_bus
  typedef logic [AW-1:0] addr_t;
  typedef logic [DW-1:0] data_t;
  typedef logic [STRB_WIDTH-1:0] strb_t;
  `REG_BUS_TYPEDEF_ALL(reg_bus, addr_t, data_t, strb_t)

  reg_bus_req_t s_reg_req;
  reg_bus_rsp_t s_reg_rsp;
  
  // Assign SV interface to structs
  `REG_BUS_ASSIGN_TO_REQ(s_reg_req, regbus_slave)
  `REG_BUS_ASSIGN_FROM_RSP(regbus_slave, s_reg_rsp)

  

  pulser_core_reg_top #(
    .reg_req_t(reg_bus_req_t),
    .reg_rsp_t(reg_bus_rsp_t),
    .AW(AW)
  ) i_regs (
    .clk_i,
    .rst_ni,
    .reg_req_i(s_reg_req),
    .reg_rsp_o(s_reg_rsp),
    .reg2hw, // Write
    .hw2reg, // Read
    .devmode_i
  );
  
endmodule


