// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package pulser_core_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 5;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {
      logic [15:0] q;
    } switchval;
    struct packed {
      logic [15:0] q;
    } endval;
  } pulser_core_reg2hw_cfg_f1_reg_t;

  typedef struct packed {
    struct packed {
      logic [15:0] q;
    } switchval;
    struct packed {
      logic [15:0] q;
    } endval;
  } pulser_core_reg2hw_cfg_f2_reg_t;

  typedef struct packed {
    struct packed {
      logic [7:0]  q;
    } f1;
    struct packed {
      logic [7:0]  q;
    } f2;
    struct packed {
      logic [7:0]  q;
    } cnt_stop;
  } pulser_core_reg2hw_cfg_cnt_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } invert_out;
    struct packed {
      logic        q;
    } idle_out;
  } pulser_core_reg2hw_ctrl_out_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
      logic        de;
    } ready;
    struct packed {
      logic [2:0]  d;
      logic        de;
    } state;
  } pulser_core_hw2reg_status_reg_t;

  // Register -> HW type
  typedef struct packed {
    pulser_core_reg2hw_cfg_f1_reg_t cfg_f1; // [89:58]
    pulser_core_reg2hw_cfg_f2_reg_t cfg_f2; // [57:26]
    pulser_core_reg2hw_cfg_cnt_reg_t cfg_cnt; // [25:2]
    pulser_core_reg2hw_ctrl_out_reg_t ctrl_out; // [1:0]
  } pulser_core_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    pulser_core_hw2reg_status_reg_t status; // [5:0]
  } pulser_core_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] PULSER_CORE_CFG_F1_OFFSET = 5'h 0;
  parameter logic [BlockAw-1:0] PULSER_CORE_CFG_F2_OFFSET = 5'h 4;
  parameter logic [BlockAw-1:0] PULSER_CORE_CFG_CNT_OFFSET = 5'h 8;
  parameter logic [BlockAw-1:0] PULSER_CORE_STATUS_OFFSET = 5'h c;
  parameter logic [BlockAw-1:0] PULSER_CORE_CTRL_OUT_OFFSET = 5'h 10;

  // Register index
  typedef enum int {
    PULSER_CORE_CFG_F1,
    PULSER_CORE_CFG_F2,
    PULSER_CORE_CFG_CNT,
    PULSER_CORE_STATUS,
    PULSER_CORE_CTRL_OUT
  } pulser_core_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] PULSER_CORE_PERMIT [5] = '{
    4'b 1111, // index[0] PULSER_CORE_CFG_F1
    4'b 1111, // index[1] PULSER_CORE_CFG_F2
    4'b 0111, // index[2] PULSER_CORE_CFG_CNT
    4'b 0001, // index[3] PULSER_CORE_STATUS
    4'b 0001  // index[4] PULSER_CORE_CTRL_OUT
  };

endpackage

